### ISSUE TITLE
Name fix

### ISSUE THREAD

**Issue by jay-ramani** [eedeidk/PulseAudio-IRSs#1]
Thank you so much for sharing this treasure. You might want to fix the name for https://github.com/eedeidk/PulseAudio-IRSs/blob/master/IRS/%252F%252F.sound.irs though.

Cheers.

**Comment by eedeidk** [comment]
done. #https://github.com/eedeidk/PulseAudio-IRSs/commit/5ad1a35f95ce6161e748ea1f9d253711a901301e
